FUNCTION

In [13]:
def addition(a,b):
    return a+b

In [54]:
def tax(sal):
    if sal>0 and sal<10000:
        return 0.05*sal
    elif sal>=10000 and sal<50000:
        return 0.1*sal
         
    elif sal>=50000 and sal<200000:
       return 0.15*sal
    elif sal>=200000:
       return 0.20*sal
    else:
        return "invalid"

In [14]:
sal=float(input("enter the sal"))
tax1=tax(sal)
print(tax1)

enter the sal 5000


NameError: name 'tax' is not defined

In [ ]:
Loops

In [ ]:
w=[67,45,23,50]
h=[160,127,140,187]
for i,j in zip(w,h):
    print(i/(j*j))

In [ ]:
for i in range(len(w)):
    print(w[i]/(h[i]*h[i]))

# Numpy

In [ ]:
lst1=[10,20,45,70]
lst2=[30,40,70,90]
print(lst1+lst2)

In [29]:
import numpy as np
ar1=np.array([10,20,45,70])
ar2=np.array([30,40,70,90])
print(ar1+ar2)

[ 40  60 115 160]


In [ ]:
arr1=np.zeros((2,3))
print(arr1)

In [ ]:
arr2=np.ones((2,3))
print(arr2)

In [ ]:
arr3=np.eye(3)
print(arr3)

In [ ]:
arr4=np.array([[3,4,5],[9,5,0]])
print(arr4)
print(np.ndim(arr4))


In [ ]:
arr5=np.array([6,7,8,9,9,4,2,1])

In [ ]:
arr5.reshape(4,2)

In [ ]:
arr6=np.array([6,7,8,9,9,4,2,1])

In [ ]:
arr6.resize(4,2)


In [ ]:
arr6

In [ ]:
arr6=np.arange(10,50).reshape(8,5)
print(arr6)
print(np.shape(arr6))

In [ ]:
arr7=np.arange(8,1001,8)
print(arr7)
print(np.shape(arr7))


In [ ]:
mult_seven=np.arange(7,701,7)
print(mult_seven)

In [ ]:
arr9=np.linspace(2,8,6)
print(arr9)

In [ ]:
arr10=np.array([[[1,2,3],[6,7,8]],[[4,5,2],[3,6,0]]])
print(arr10)
print(np.shape(arr10))
print(np.ndim(arr10))

In [ ]:
mat1=np.array([9,4,6,7]).reshape(2,2)
mat2=np.array([1,2,3,4]).reshape(2,2)
print("matrix 1:\n",mat1)
print("matrix 2:\n",mat2)

In [ ]:
print(mat1*mat2)

In [ ]:
print(mat1.dot(mat2))

In [ ]:
print(np.linalg.inv(mat1))

In [ ]:
print(np.linalg.inv(mat2))

statistics

In [ ]:
arr1=np.array([90,45,34,16,23,12])
print(np.mean(arr1))

In [ ]:
print(np.median(arr1))

varriance

trigonometry

In [ ]:
print(np.pi)

In [ ]:
rad=[90,30,45]
for i in rad:
    print(np.sin(i))

In [ ]:
rad=[90,30,45]
for i in rad:
    print(np.cos(i))

In [ ]:
rad=[90,30,45]
for i in rad:
    print(np.tan(i))

In [ ]:
deg=[np.pi/4,np.pi/2,np.pi/3]
for i in deg:
    print(np.sin(i))

Arithematic operations

In [ ]:
a=np.array([8,9,1])
b=np.array([2,5,8])
print(np.sum((a,b)))

In [ ]:
s1=np.array([90,23,40,12])
s2=np.array([10,2,11,5])
print(np.mod(s1,s2))


In [ ]:
print(np.divmod(s1,s2))

In [ ]:
A=np.array([56,78,12,32,111,109])
print(max(A))

sorting

In [ ]:
B=np.array([90,12,45,1,89,98])
B.sort()
print(B)

In [ ]:
c=np.array([90,12,45,1,89,98])
D=sorted(c)
print(c)
print(D)

Rounding

In [ ]:
s2=np.array([9.1,-7.8])
print(np.ceil(s2))

In [ ]:
print(np.floor(s2))

Random module

In [20]:
import numpy.random as rd

In [21]:
ran1=rd.rand(2)
print(ran1)

[0.75793132 0.68147924]


In [22]:
ran2=rd.randint(5)
print(ran2)

4


In [27]:
ran3= rd.randint(5,size=(6,7,3))
print(ran3)

[[[1 2 3]
  [4 4 2]
  [2 2 1]
  [4 0 2]
  [3 1 0]
  [0 4 4]
  [2 3 0]]

 [[1 3 4]
  [3 0 1]
  [4 2 0]
  [2 0 2]
  [2 1 1]
  [3 0 3]
  [2 4 2]]

 [[3 4 1]
  [0 2 4]
  [2 0 0]
  [3 2 1]
  [4 1 0]
  [3 1 1]
  [1 4 1]]

 [[3 1 1]
  [1 1 4]
  [3 4 0]
  [4 0 2]
  [4 0 0]
  [3 3 1]
  [2 3 4]]

 [[3 4 2]
  [2 2 3]
  [0 3 0]
  [2 2 4]
  [3 2 1]
  [4 1 3]
  [2 3 2]]

 [[1 4 4]
  [0 1 1]
  [3 3 1]
  [2 4 4]
  [4 4 2]
  [2 2 4]
  [1 4 1]]]


stack

In [34]:
Ar1=np.array([[9,4,23],[3,4,5]])
Ar2=np.array([[8,1,2],[33,42,51]])
print(Ar1)
print("\n")
print(Ar2)

[[ 9  4 23]
 [ 3  4  5]]


[[ 8  1  2]
 [33 42 51]]


In [36]:
Ar3=np.arange(1,13).reshape(3,2,2)
print(Ar3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [39]:
Ar4=np.dstack(Ar3)
print(Ar4)


[[[ 1  5  9]
  [ 2  6 10]]

 [[ 3  7 11]
  [ 4  8 12]]]


In [40]:
num1=81
num2=99
num3=78
print(np.sqrt(num1))

9.0


In [41]:
print(np.lcm(num1,num2))

891


In [42]:
print(np.gcd(num1,num2))

9


In [43]:
AA=[45,67,89]
print(np.lcm.reduce(AA))

268335


In [44]:
print(np.gcd.reduce(AA))

1


In [46]:
AB=np.array([0,-5,7,-25])
print(np.absolute(AB))

[ 0  5  7 25]


Logarithms

In [47]:
n=45
print(np.log(n))

3.8066624897703196


In [48]:
print(np.log2(n))

5.491853096329675


Set

In [49]:
s1=np.array([9,3,5,2,1])
s2=np.array([4,5,2,1,3])
print(s1,"\n")
print(s2)

[9 3 5 2 1] 

[4 5 2 1 3]


In [51]:
print(np.union1d(s1,s2))

[1 2 3 4 5 9]


In [53]:
print(np.intersect1d(s1,s2))

[1 2 3 5]


In [55]:
print(np.setdiff1d(s1,s2))

[9]


Search

In [58]:
cal1=np.array([44,33,12,67,19])
Index=np.where(cal1%2==2)
print(Index)

(array([], dtype=int64),)


In [67]:
cal2=np.array([45,33,21,50,60,15])
Index=np.where((cal2%3==0)&(cal2%5==0))
print(Index)

(array([0, 4, 5], dtype=int64),)
